# @file         livingroom-thermostat-relay.yaml
# @author       
# @description  Single-point Thermostat Relay unit
# @version      0.3.1.
# @section      Board 
#   - wemos D1 mini Pro
# @section      BOM
#   - Display:
#     64x48 OLED shield
#   - Relay:
#     1ch Relay (5V)
#   - Buttons:
#     1 push button for manually ON/OFF
# @library
#   - bme680 sensor bsec library
# @include
# @library
# @description
# @TODO
#   - RF for using wo HA

######################################
# SUBSTITUIONS SECTION
######################################
substitutions:
  device_type: Thermostat
  device_subtype: Relay
  device_number: "1"
  device_name: thermostat-relay-${device_number}
  device_group: Climate

  device_location: Livingroom
  device_floor: Ground floor

  unit_name: relay
  parent_device: "thermostat-central-1"
  child_devices: "{switch_heater_1}"
  controlled_device: heater

  <<: !include includes/base/.base.substitutions.yaml

  # MQTT topic prefix for testing
  <<: !include includes/mqtt/.mqtt.topic-prefix.yaml
  # MQTT default topics
  <<: !include includes/mqtt/.mqtt.default-topics.yaml
  # MQTT device specific topics

  # Homeassistant entities for temperature
  <<: !include includes/ha/.ha.entities-temperature.yaml

######################################
# ESPHOME SECTION
######################################
esphome:
  # Project/Board definition
  <<: !include includes/base/.base.esphome-definition.yaml
  # Board type
  <<: !include includes/boards/.board.wemos-d1-mini-pro.yaml
  project:
    <<: !include includes/projects/livingroom-thermostat/.versioning.livingroom-thermostat.yaml
  on_boot:
    priority: 200
    then:
      - switch.turn_off: switch_heater_1
      - switch.turn_on: switch_manual_auto
      - lambda: |-
          ESP_LOGI("separator", "------------------------------------------------------");
          ESP_LOGI("on_boot", "Heater Turned Off and Auto switch turned on after boot!");
  on_shutdown:
    priority: 700
    then:
      - switch.turn_off: switch_heater_1
      # deepsleep

######################################
# PACKAGES SECTION
######################################
packages:
  mqtt: !include includes/mqtt/.mqtt.base-params.yaml
  text_sensor: !include includes/components/.components.text_sensor.wifi-connection-data.yaml

######################################
# Connection SECTION: wifi, api, ota
######################################
<<: !include includes/base/.base.connection-settings.yaml

logger:
  level: INFO
  
######################################
# HA DATE-TYME SYNC SECTION
######################################
<<: !include includes/ha/.ha.time-sync.yaml

######################################
# DEEP-SLEEP SECTION
######################################
#deep_sleep:
#  id: deep_sleep_1
#  run_duration: 20s
#  sleep_duration: 5min

######################################
# MQTT SECTION
######################################
mqtt:
  on_connect:
    - switch.turn_off: switch_heater_1
    - lambda: |- 
        id(state_mqtt_connection) = true;
        id(switch_manual_auto).turn_off(); // AUTO MODE
        id(state_auto_mode) = true;     // AUTO MODE
        ESP_LOGI("separator", "------------------------------------------------------");
        ESP_LOGI("mqtt", "${device_type} ${device_subtype} ${device_number} connected to MQTT");
  #<<: !include includes/mqtt/.mqtt.default-on_disconnect.yaml
  on_disconnect:
    - switch.turn_off: switch_heater_1
    - lambda: |-
        ESP_LOGI("separator", "------------------------------------------------------");
        ESP_LOGI("mqtt", "${device_type} ${device_subtype} ${device_number} disconnected from MQTT");

  # smarthome_test/Climate/Livingroom/Thermostat/command
  on_json_message:
    # Central Unit send command for turning ON | OFF Heater
    - topic: ${topic_command}
      then:
        - lambda: |-
            if (x.containsKey("receiver") && x["receiver"] == "${device_name}") {
              ESP_LOGI("separator", "------------------------------------------------------");
              
              if (x["payload"]["command"] == "ON" ) {
                id(state_auto_mode) = true;
                id(switch_heater_1).turn_on();
                id(switch_manual_auto).turn_off(); // AUTO MODE
                ESP_LOGI("mqtt",  "MQTT JSON Message: ON");
              }
              if (x["payload"]["command"] == "OFF" ) {
                id(state_auto_mode) = true;
                id(switch_heater_1).turn_off();
                //id(switch_manual_auto).turn_on();  // MANUAL MODE
                ESP_LOGI("mqtt",  "MQTT JSON Message: OFF");
              }
              if (x["payload"]["command"] == "IDLE" ) {
                id(state_auto_mode) = true;
                id(switch_heater_1).turn_off();
                id(switch_manual_auto).turn_off();  // MANUAL MODE
                ESP_LOGI("mqtt",  "MQTT JSON Message: IDLE");
              }
              if (x["payload"]["command"] == "RESTART" ) {
                ESP_LOGI("separator", "------------------------------------------------------");
                ESP_LOGI("MQTT","RESTART command received");
                id(restart_switch).turn_on();
              }
            }

######################################
# GLOBALS SECTION
######################################
globals:
  ######################################
  # Check API connection status
  ######################################
  - id: state_api_connected           
    type: bool
    restore_value: false
    initial_value: 'false'
  ######################################
  # Check MQTT connection status
  ######################################
  - id: state_mqtt_connection
    type: bool
    restore_value: true
    initial_value: 'false'
  ######################################
  # AUTO / MANUAL MODE
  # The "id: switch_heater_1" HA SWITCH or "id: heater_button" Push button can change MANUAL / AUTO state
  # IN MANUAL mode send message to Central Unit to DISABLE Heater and AC button
  # IN AUTO mode send message to Central Unit to ENABLE Heater and AC button
  # TRUE : AUTO | FALSE : MANUAL
  ######################################
  - id: state_auto_mode   # AUTO | MANUAL
    type: bool
    restore_value: false
    initial_value: 'true'
  ######################################
  # Check API connection status
  ######################################
  - id: set_temp_in
    type: std::string
    restore_value: false
    initial_value: '"21.00"'

######################################
# INTERVAL SECTION
######################################
interval:
  - interval: 10s
    then:
      - display.page.show_next: mini_oled
      #- component.update: mini_oled

######################################
# I2C SECTION
######################################
i2c:
  - id: i2cbus_ssd1306
    sda: D2
    scl: D1

######################################
# FONT SECTION
######################################
font:
  - file: 'fonts/wef.ttf'
    id: font_wef_9
    size: 13
  - file: 'fonts/Roboto-Regular.ttf'
    id: roboto_regular_9
    size: 10


######################################
# 0.96" DISPLAY SECTION
######################################
display:
  - platform: ssd1306_i2c
    model: "SSD1306 64x48"
    i2c_id: i2cbus_ssd1306
    reset_pin: D0
    address: 0x3C
    id: mini_oled
    pages:
      - id: page1
        lambda: |-
          // LINE 1
          // Manual/Auto state
          it.print(0, 0, id(roboto_regular_9), id(state_auto_mode) ? "AUTO":"MANUAL");
          // LINE 2
          // MQTT state
          it.print(0, 13, id(roboto_regular_9), id(state_mqtt_connection) ? "CONNECTED":"DISCONNECTED");
          // LINE 3
          // Heater state
          it.print(0, 26, id(roboto_regular_9), id(switch_heater_1).state ? "HEATING":"IDLE");
      - id: page2
        lambda: |-
          // LINE 1
          //Outside temp
          it.print(0, 0, id(roboto_regular_9), "Out:");
          if (id(owm_weather_temperature).has_state()) {
            it.printf(26, 0, id(roboto_regular_9), "%.0f°C", id(owm_weather_temperature).state);
          }
          // LINE 2
          //Ambiente temp
          it.print(0, 13, id(roboto_regular_9), "In:");
          if (id(bme680_temperature).has_state()) {
            it.printf(26, 13, id(roboto_regular_9), "%.0f°C", id(bme680_temperature).state);
          }
          // LINE 3
          // Print time in HH:MM format
          it.strftime(63, 26, id(roboto_regular_9), TextAlign::RIGHT, "%H:%M", id(homeassistant_time).now());
          // LINE 4
          // Print date in YYYY.MM.DD format
          it.strftime(63, 37, id(roboto_regular_9), TextAlign::RIGHT, "%Y.%m.%d", id(homeassistant_time).now());

######################################
# SWITCH SECTION
######################################
switch:
  - platform: restart
    name: "Restart"
    id: restart_switch
  ######################################
  # HA switch to turn ON/OFF heater
  # internal led
  ######################################
  - platform: gpio
    pin: GPIO00
    name: "Heater switch"
    id: switch_heater_1
    inverted: true
    restore_mode: ALWAYS_OFF
    <<: !include { file: includes/mqtt/.mqtt.components-topic-with-command.yaml, vars: { component_type: "switch", component_id: "heater_switch" } } # inline syntax
    on_turn_on:
      - lambda: |-
          ESP_LOGI("separator", "------------------------------------------------------");
          ESP_LOGI("heater_switch", "Heater Turned On by Control unit!");
          id(state_auto_mode) = true;
          id(switch_heater_1).turn_on();
      - mqtt.publish_json:
            topic: ${topic_action_receiver}
            payload: |-
              root["sender"] = "${device_type}_${device_subtype}_${device_number}";
              root["receiver"] = "${device_type}_${device_subtype}_${device_number}";
              root["room"] = "${device_location}";
              root["floor"] = "${device_floor}";
              root["payload"]["action"] = "ON";
              root["trigger"] = "switch on_turn_on";
              root["timestamp"] = id(homeassistant_time).now().timestamp;
    on_turn_off:
      - lambda: |-
            ESP_LOGI("separator", "------------------------------------------------------");
            ESP_LOGI("heater_switch", "Heater Turned Off by Control unit!");
            id(state_auto_mode) = true;
            id(switch_heater_1).turn_off();
            id(switch_manual_auto).turn_off();
      - mqtt.publish_json:
            topic: ${topic_action_receiver}
            payload: !lambda |-
              root["sender"] = "${device_type}_${device_subtype}_${device_number}";
              root["receiver"] = "${device_type}_${device_subtype}_${device_number}";
              root["room"] = "${device_location}";
              root["floor"] = "${device_floor}";
              root["payload"]["action"] = id(switch_heater_1).state ? "ON" : "OFF";
              root["trigger"] = "switch on_turn_off";
              root["timestamp"] = id(homeassistant_time).now().timestamp;
  ######################################
  # MANUAL / AUTO status LED
  ######################################
  - platform: gpio
    pin: D7
    name: "Manual/Auto control LED"
    id: switch_manual_auto
    <<: !include { file: includes/mqtt/.mqtt.components-topic-with-command.yaml, vars: { component_type: "switch", component_id: "manual_auto_switch" } } # inline syntax
    on_turn_on: # MANUAL MODE
      - switch.turn_on: switch_heater_1
      - lambda: id(state_auto_mode) = false;
      - mqtt.publish_json:
          topic: ${topic_command}
          payload: |-
            root["sender"] = "${device_type}_${device_subtype}_${device_number}";
            root["receiver"] = "${parent_device}";
            root["room"] = "${device_location}";
            root["floor"] = "${device_floor}";
            root["payload"]["command"] = "ON";
            root["payload"]["description"] = "Manual mode is ON | Auto mode is OFF";
            root["trigger"] = "switch on_turn_on";
            root["timestamp"] = id(homeassistant_time).now().timestamp;
    on_turn_off: # AUTO MODE
      - switch.turn_off: switch_heater_1
      - lambda: id(state_auto_mode) = true;
      - mqtt.publish_json:
          topic: ${topic_command}
          payload: |-
            root["sender"] = "${device_type}_${device_subtype}_${device_number}";
            root["receiver"] = "${parent_device}";
            root["room"] = "${device_location}";
            root["floor"] = "${device_floor}";
            root["payload"]["command"] = "OFF";
            root["payload"]["description"] = "Manual mode is OFF | Auto mode is ON";
            root["trigger"] = "switch on_turn_off";
            root["timestamp"] = id(homeassistant_time).now().timestamp;

######################################
# SENSOR SECTION
######################################
sensor:
  # OpenWeatherMap sensor.openweathermap_temperature
  - platform: homeassistant
    name: "OpenWeatherMap Temperature"
    entity_id: sensor.openweathermap_temperature
    id: owm_weather_temperature
    internal: true
    on_value:
      then:
        - lambda: |-
            ESP_LOGI("separator", "------------------------------------------------------");
            ESP_LOGI("OpenWeatherMap", "The Outtemp value is temperature=%f", id(owm_weather_temperature).state);
  # Control unit BME680 temp
  - platform: homeassistant
    id: bme680_temperature
    entity_id: ${thermostat_central_temperature_entity}
    # attribute: temperature
    internal: true

######################################
# BINARY SENSOR SECTION
######################################
binary_sensor:
  ######################################
  # Device status
  ######################################
  #<<: !include includes/components/.components.binary_sensor.device-status.yaml
  
  ######################################
  # Push Button to turn ON/OFF heater manually
  ######################################
  - platform: gpio
    name: "Heater button"
    id: heater_button
    <<: !include { file: includes/mqtt/.mqtt.components-topic.yaml, vars: { component_type: "switch", component_id: "heater_button" } } # inline syntax
    pin: 
      number: D4
      inverted: true
      mode: 
        input: true
        pullup: true
    filters:
      - delayed_on_off: 100ms
    on_press:
      - switch.toggle: switch_manual_auto
      - lambda: |-
          ESP_LOGI("separator", "------------------------------------------------------");
          ESP_LOGI("heater_button", "AUTO MODE %s", id(state_auto_mode)?"True":"False");

######################################
# TEXT SENSOR SECTION
######################################

#####################################
# BUTTON SECTION
######################################
button:
  <<: !include includes/components/.components.button.restart.yaml
  <<: !include includes/components/.components.button.restart-factory.yaml