# esp32-cam AI-Thinker board
# enc: ZChn4u6GJ/rwS5+W/AlfZ82y4qsTcbfpvoy8dGP151k=

######################################
# SUBSTITUIONS SECTION
######################################
substitutions:
  device_type: Camera
  device_subtype: Indoor
  device_number: "1"
  device_name: camera-indoor-${device_number}
  device_group: Survillance

  device_location: Livingroom
  device_floor: Ground floor

  unit_name: ""
  parent_device: "_"
  child_devices: "{}"
  controlled_device: ""

  <<: !include includes/base/.base.substitutions.yaml

  # MQTT topic prefix for testing
  <<: !include includes/mqtt/.mqtt.topic-prefix.yaml
  # MQTT default topics
  <<: !include includes/mqtt/.mqtt.default-topics.yaml
  # MQTT device specific topics

######################################
# ESPHOME SECTION
######################################
esphome:
  # Project/Board definition
  <<: !include includes/base/.base.esphome-definition.yaml
  # Board type
  <<: !include includes/boards/.board.esp32-cam.yaml
  project:
    <<: !include includes/projects/livingroom-cam.yaml

######################################
# PACKAGES SECTION
######################################
packages:
  mqtt: !include includes/mqtt/.mqtt.base-params.yaml
  text_sensor: !include includes/components/.components.text_sensor.wifi-connection-data.yaml

######################################
# Connection SECTION: wifi, api, ota
######################################
<<: !include includes/base/.base.connection-settings.yaml

######################################
# HA DATE-TYME SYNC SECTION
######################################
<<: !include includes/ha/.ha.time-sync.yaml

######################################
# DEEP-SLEEP SECTION
######################################
#deep_sleep:
#  id: deep_sleep_1
#  run_duration: 20s
#  sleep_duration: 5min

######################################
# MQTT SECTION
######################################
mqtt:
  on_connect:
    - logger.log: "${device_type} ${device_subtype} ${device_number} connected"
  on_disconnect:
    - logger.log: "${device_type} ${device_subtype} ${device_number} disconnected"

######################################
# ESP32 CAM SECTION
######################################
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: Image

# Image/Video settings, https://esphome.io/components/esp32_camera.html

  max_framerate: 10 fps    # default: 10 fps, max 60
  idle_framerate: 0.2 fps # default: 0.1 fps - framerate for 'picture' in HA dashboard
  resolution: 1024x768
  jpeg_quality: 8
  vertical_flip: False
  horizontal_mirror: False
  contrast: 0 # default: 0, variable -2 to 2
  brightness: 0 # default: 0, variable -2 to 2
  saturation: 0 # default: 0, variable -2 to 2
  
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

######################################
# OUTPUT SECTION
######################################
output:
  #flashlight
  - platform: gpio
    pin: GPIO4
    id: gpio_4

######################################
# LIGHT SECTION
######################################
light:
  #flashlight
  - platform: binary
    output: gpio_4
    name: Light
    <<: !include { file: includes/mqtt/.mqtt.components-topic.yaml, vars: { component_type: "light", component_id: "flashlight" } } # inline syntax

######################################
# SENSOR SECTION
######################################
sensor:
  - platform: uptime
    name: Uptime
    <<: !include { file: includes/mqtt/.mqtt.components-topic.yaml, vars: { component_type: "sensor", component_id: "uptime" } } # inline syntax

######################################
# SWITCH SECTION
######################################

######################################
# TEXT SENSOR SECTION
######################################

#####################################
# BUTTON SECTION
######################################
button:
  <<: !include includes/components/.components.button.restart.yaml
  <<: !include includes/components/.components.button.restart-factory.yaml